services:
  mysql:
    image: mysql:8.0
    container_name: medical-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Promass@2026
      MYSQL_DATABASE: medical_appointments
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
